version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_service_node_app
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - DATABASE_URL=postgresql://postgres:postgrespw@host.docker.internal:5432/backend_node?schema=public
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - MESSAGING_ENABLED=true
      - RABBIT_URL=amqp://guest:guest@host.docker.internal:5672
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
